<?php
    $title = "Adicionando nova pessoa";
    $this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php

$form->setAttribute('action', $this->url('pessoa', ['action' => 'adicionar']));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$nome = $this->form->get('nome');
$sobrenome = $this->form->get('sobrenome');
$email = $this->form->get('email');
$situacao = $this->form->get('situacao');

$nome->setAttribute('class', 'form-control');
$nome->setAttribute('autofocus', 'autofocus');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary btn-lg');
?>

<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($nome) ?>
        <?= $this->formElement($nome) ?>
        <?= $this->formElementErrors($nome)->render($nome, ['class' => 'help-block']) ?>
    </div>
</div>
